swagger: '2.0'
info:
  description: 为API生，为框架死，为debug奋斗一辈子；吃符号亏，上大小写的当，最后死在需求上   ------- 梦旋飞
  version: 1.0.0
  title: 开发平台

basePath: /ld_dlj_interface

schemes:
  - http

#认证
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "token"
    in: "header"

#定义接口数据
paths:
  /menu/list:
    post:
      tags:
        - 菜單管理
      summary: 获取菜单
      produces:
        - application/json
      parameters:
        - name: pid
          description: 父级id，左侧菜单用0.右边tab传左侧导航栏id，如果右侧有上下布局，则依次往下绑定了关系
          in: query
          type: string
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'


  /industryClass/getData:
    post:
      tags:
        - 行业分类模块接口
      summary: 基础数据：当前用户数，同比，环比，用户量，装机容量，电量，产能利用率
      produces:
        - application/json
      parameters:
        - name: industryId
          description: 行业id
          in: query
          type: string
          required: true
        - name: timeType
          description:  查询时间类型 1按年，2按月。
          in: query
          type: string
          required: true

      responses:
        '200':
          schema:
            $ref: '#/definitions/R'


  /common/savaDate:
    post:
      tags:
        - 公用接口
      summary: 入库excel
      produces:
        - application/json
      parameters:
        - name: url
          description: 路径
          in: query
          type: string
          required: true
        - name: time
          description: 时间 2020-03
          in: query
          type: string
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'




  /industryClass/getDisData:
    post:
      tags:
        - 行业分类模块接口
      summary: 折现图数据
      produces:
        - application/json
      parameters:
        - name: industryId
          description: 行业id
          in: query
          type: string
          required: true
        - name: type
          description: 类型 1.用户量 2.装机容量 3.电量 4.产能利用率
          in: query
          type: string
          required: true
        - name: timeType
          description: 查询时间类型 1按年，2按月。
          in: query
          type: string
          required: true

      responses:
        '200':
          schema:
            $ref: '#/definitions/R'




  /industryClass/getLastYearEleCon:
    post:
      tags:
        - 行业分类模块接口
      summary: 上年度居民用电比例
      produces:
        - application/json
      parameters:
        - name: startTime
          description: 开始时间 YYYY 数据从2017年开始。如果查询的是2017年，那么开始时间和结束时间就是2017-2018
          in: query
          type: string
          required: true
        - name: endTime
          description: 结束时间 YYYY
          in: query
          type: string
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'




  /industryClass/getMonthCapUtil:
    post:
      tags:
        - 行业分类模块接口
      summary: 获取产能排行前五的产业
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'





  #高耗能行业产能利用率情况模块
  /highCon/getData:
    post:
      tags:
        - 高耗能行业产能利用率情况模块接口
      summary: 基础数据。接口同行业分类模块基础数据接口一致，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'



  /highCon/getDisData:
    post:
      tags:
        - 高耗能行业产能利用率情况模块接口
      summary: 折线图数据。接口同行业分类模块折现图接口一致，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'



  #第一产业产能利用率情况
  /priIndCon/getData:
    post:
      tags:
        - 第一产业产能利用率情况模块接口
      summary: 基础数据。接口同行业分类模块基础数据接口一致，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'



  /priIndCon/getDisData:
    post:
      tags:
        - 第一产业产能利用率情况模块接口
      summary: 折线图数据。接口同行业分类模块折现图接口一致，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'





  #第三产业产能利用率情况
  /threeIndCon/getData:
    post:
      tags:
        - 第三产业产能利用率情况模块接口
      summary: 基础数据。接口同行业分类模块基础数据接口一致，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'



  /threeIndCon/getDisData:
    post:
      tags:
        - 第三产业产能利用率情况模块接口
      summary: 折线图数据。接口同行业分类模块折现图接口一致，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'





  #各行业产能利用率情况
  /varIndCon/getDisData:
    post:
      tags:
        - 各行业产能利用率情况模块接口
      summary: 折线图数据。接口同行业分类模块折现图接口一致，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'


  /varIndCon/getIndList:
    post:
      tags:
        - 各行业产能利用率情况模块接口
      summary: 获取所有行业树结构
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'


  /varIndCon/getData:
    post:
      tags:
        - 各行业产能利用率情况模块接口
      summary: 基础数据。接口同行业分类模块基础数据接口一致，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'




  #大用户业扩报装投资建议等级
  /BigUserIndExpanCon/getIndList:
    post:
      tags:
        - 大用户业扩报装投资建议等级模块接口
      summary: 获取所有行业树结构。同各行业产能利用率情况模块一样，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'

  /bigUserIndExpanCon/getDisData:
    post:
      tags:
        - 大用户业扩报装投资建议等级模块接口
      summary: 折线图数据。接口同行业分类模块折现图接口一致，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'

  /bigUserIndExpanCon/getData:
    post:
      tags:
        - 大用户业扩报装投资建议等级模块接口
      summary: 基础数据。接口同行业分类模块基础数据接口一致，请求路径也一致。此接口路径只做api提示用
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'



  /BigUserIndExpanCon/getInvSug:
    post:
      tags:
        - 大用户业扩报装投资建议等级模块接口
      summary: 用户业扩报装投资建议等级
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'










#定义数据模型
definitions:
  R:
      type: object
      properties:
        code:
          description: 状态码 0：成功  非0：失败
          type: integer
          format: int32
        msg:
          description: 失败原因
          type: string
