swagger: '2.0'
info:
  description: 为API生，为框架死，为debug奋斗一辈子；吃符号亏，上大小写的当，最后死在需求上   ------- 梦旋飞
  version: 1.0.0
  title: 开发平台

basePath: /ld_dlj_interface

schemes:
  - http

#认证
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "token"
    in: "header"

#定义接口数据
paths:
  /sys/login:
    post:
      tags:
        - 菜單管理
      summary: 菜單列表
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'





#定义数据模型
definitions:
  R:
      type: object
      properties:
        code:
          description: 状态码 0：成功  非0：失败
          type: integer
          format: int32
        msg:
          description: 失败原因
          type: string
